#!/usr/bin/env bash
# setup-regions.sh — interactive helper that writes a regions.txt for your
# own matchmaking infrastructure. Run it after cloning, before build/dist:
#
#   bash setup-regions.sh                # writes ./regions.txt
#   bash setup-regions.sh my-regions.txt # custom output path
#
# The resulting file can be shipped with a build (REGIONS_FILE=regions.txt
# bash dist.sh pc) or dropped next to an installed 3sx binary. Format is one
# region per line: code|label|host|port (max 16 entries).
set -euo pipefail

OUT="${1:-regions.txt}"

if [ -f "$OUT" ]; then
    printf '%s already exists. Overwrite? [y/N] ' "$OUT"
    read -r ans
    case "$ans" in
        y|Y) ;;
        *) echo "aborted."; exit 1 ;;
    esac
fi

echo "Each region is a matchmaking server endpoint your players can pick"
echo "from in-game. The client pings every entry at startup and pre-selects"
echo "the lowest-latency one. Press Enter on an empty 'code' to finish."
echo

entries=()
i=1
while [ "$i" -le 16 ]; do
    printf 'region %d code (e.g. us-east-1, empty to finish): ' "$i"
    read -r code
    [ -z "$code" ] && break
    case "$code" in
        *'|'*) echo "  code must not contain '|'"; continue ;;
    esac

    printf '  label shown in the picker [%s]: ' "$code"
    read -r label
    label="${label:-$code}"

    printf '  host (IP or DNS name): '
    read -r host
    if [ -z "$host" ]; then
        echo "  host is required, entry discarded."
        continue
    fi

    printf '  TCP port [19000]: '
    read -r port
    port="${port:-19000}"
    case "$port" in
        ''|*[!0-9]*) echo "  port must be numeric, entry discarded."; continue ;;
    esac

    entries+=("$code|$label|$host|$port")
    i=$((i + 1))
    echo
done

if [ "${#entries[@]}" -eq 0 ]; then
    echo "no regions entered — nothing written."
    exit 1
fi

{
    echo "# regions.txt — generated by setup-regions.sh"
    echo "# code|label|host|port"
    printf '%s\n' "${entries[@]}"
} > "$OUT"

echo "wrote ${#entries[@]} region(s) to $OUT:"
sed 's/^/  /' "$OUT"
echo
echo "Next steps:"
echo "  - bundle it into a release:  REGIONS_FILE=$OUT bash dist.sh pc <version>"
echo "  - or test locally: copy it next to 3sx.exe (or into the prefs dir)"
